### ISSUE TITLE
White noise

### ISSUE THREAD

**Issue by derrell** [svet-am/rivian-meridian-audio-test#1]
Rather than an off-station FM setting to generate white noise, you might be able to use Spotify-available white noise recordings, such as https://open.spotify.com/track/2COPUH8f4mlt1vzZG83zqU

**Comment by svet-am** [comment]
Hi @derrell - Thanks for your comment!

Part of the objective of this project is to evaluate the audio quality of the various streaming services in a Rivian Meridian Audio system versus standard "native" audio.  So, the white nose as generated by FM is the closest that we can currently get to that.  Any audio - even noise - from a streaming service will be subject to their respective bitrates, compression, etc.  So, this project helps to isolate from that.

As you can see from the samples in the playlists, I am already _also_ testing white, pink, and Brownian noise from the streaming services.  I have constructed the _exact same_ playlist for both Spotify and Tidal (and will for other services as they come online).  So, you can compare "native" noise to the streaming noise.

**Comment by derrell** [comment]
Got it. Thanks. Closing.
